{% set version = "3.0.2" %}

package:
  name: urwid
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/u/urwid/urwid-{{ version }}.tar.gz
  sha256: e7cb70ba1e7ff45779a5a57e43c57581ee7de6ceefb56c432491a4a6ce81eb78

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - importlib-metadata
    - setuptools >=61
    - setuptools_scm >=6.2
  run:
    - wcwidth
    - typing-extensions
    - python

test:
  imports:
    - urwid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://urwid.org/
  license: LGPL-2.1-or-later
  license_file: COPYING
  license_family: LGPL
  summary: A full-featured console (xterm et al.) user interface library
  dev_url: https://github.com/urwid/urwid
  doc_url: https://urwid.org/tutorial/index.html

extra:
  recipe-maintainers:
    - scopatz
    - asmeurer
    - ocefpaf
    - matthiasdiener
