{% set version = "2.2.1" %}

package:
  name: urwid
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/urwid/urwid-{{ version }}.tar.gz
  sha256: e33911ab18f2c73fddbe9bf216d021e74e20b2d5aa9be30403c58f55131bb8a1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - urwid
    - urwid.tests

about:
  home: https://urwid.org/
  license: LGPL-2.1-or-later
  license_file: COPYING
  license_family: LGPL
  summary: A full-featured console (xterm et al.) user interface library
  dev_url: https://github.com/urwid/urwid
  doc_url: https://urwid.org/tutorial/index.html

extra:
  recipe-maintainers:
    - scopatz
    - asmeurer
    - ocefpaf
    - matthiasdiener
