{% set version = "4.0.0" %}

package:
  name: urwid
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/u/urwid/urwid-{{ version }}.tar.gz
  sha256: 58ddc5c65eb3109b69e2e95469553f9f86070645cc1b553d6ee3fe8dbac2e0ba

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - importlib-metadata
    - setuptools >=61
    - setuptools_scm >=6.2
  run:
    - wcwidth >=0.4
    - typing-extensions
    - python >={{ python_min }}.*

test:
  imports:
    - urwid
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://urwid.org/
  license: LGPL-2.1-or-later
  license_file: COPYING
  license_family: LGPL
  summary: A full-featured console (xterm et al.) user interface library
  dev_url: https://github.com/urwid/urwid
  doc_url: https://urwid.org/tutorial/index.html

extra:
  recipe-maintainers:
    - scopatz
    - asmeurer
    - ocefpaf
    - matthiasdiener
